'use client';
import {useEffect,useMemo,useState} from 'react';
type Status='待审核'|'待终审'|'已采纳'|'已退回';
type Idea={id:string;title:string;desc:string;plan:string;author:string;dept:string;date:string;status:Status;likes:number;comments:number;saved:number;adoptedAt?:string;liked?:boolean;collected?:boolean};
type Account={name:string;role:'灵感捕手'|'建议初审'|'建议终审';dept:string;points:number};
const accounts:Account[]=[
{name:'林澄',role:'灵感捕手',dept:'生产运营部',points:120},
{name:'周文清',role:'灵感捕手',dept:'智能制造部',points:240},
{name:'陈嘉言',role:'建议初审',dept:'数字化中心',points:190},
{name:'顾宁',role:'建议终审',dept:'综合管理部',points:165}];
const seed:Idea[]=[
{id:'MI-2026-042',title:'优化跨部门设备借用流程',desc:'设备借用依赖纸质登记，信息同步不及时，归还节点也难以追踪。',plan:'上线统一预约看板，绑定责任人并在归还前自动提醒。',author:'周文清',dept:'智能制造部',date:'今天 09:42',status:'待审核',likes:18,comments:6,saved:8},
{id:'MI-2026-038',title:'生产晨会增加三分钟改善分享',desc:'一线的小改善缺少轻量分享渠道，优秀经验难以快速复制。',plan:'每天由一个班组分享一项可复用改进，沉淀为现场知识卡片。',author:'林澄',dept:'生产运营部',date:'昨天 16:20',status:'待终审',likes:34,comments:11,saved:15},
{id:'MI-2026-031',title:'会议室无人使用自动释放',desc:'会议室被预约后经常无人使用，临时会议却找不到可用空间。',plan:'预约开始10分钟内无人签到，系统自动释放并通知预约人。',author:'陈嘉言',dept:'数字化中心',date:'08-18',status:'已采纳',likes:128,comments:24,saved:46,adoptedAt:'2026-08-20T09:30:00',liked:true},
{id:'MI-2026-027',title:'办公耗材设置低库存提醒',desc:'耗材补充依赖人工巡查，偶尔出现打印纸或墨盒临时短缺。',plan:'设置安全库存阈值，低于阈值时自动形成采购提醒。',author:'顾宁',dept:'综合管理部',date:'08-16',status:'已采纳',likes:86,comments:17,saved:31,adoptedAt:'2026-08-18T14:10:00'},
{id:'MI-2026-019',title:'访客登记信息一次录入',desc:'访客在不同区域重复填写相同信息，体验不佳。',plan:'通过访客码复用已授权信息。',author:'沈悦',dept:'安全环保部',date:'08-12',status:'已退回',likes:9,comments:3,saved:2}];
const nav=[['总览','⌂'],['提交建议','＋'],['我的建议','▣'],['建议广场','✦'],['审核管理','✓'],['系统管理','⚙'],['超级维护','◇']];
export default function Home(){
const[account,setAccount]=useState<Account|null>(null),[page,setPage]=useState('总览'),[items,setItems]=useState(seed),[filter,setFilter]=useState('全部'),[selected,setSelected]=useState<Idea|null>(null),[toast,setToast]=useState(''),[notice,setNotice]=useState(false),[query,setQuery]=useState(''),[userMenu,setUserMenu]=useState(false);
const filtered=useMemo(()=>items.filter(x=>{const matchesScope=page!=='我的建议'||x.author===account?.name;const matchesStatus=filter==='全部'||x.status===filter;const matchesText=x.title.includes(query)||x.desc.includes(query);const matchesPeople=['建议广场','审核管理'].includes(page)&&(x.author.includes(query)||x.dept.includes(query));return matchesScope&&matchesStatus&&(matchesText||matchesPeople)}),[items,filter,query,page,account?.name]);
useEffect(()=>setQuery(''),[page]);
if(!account)return <Login onLogin={setAccount}/>;
const role=account.role;
const pageWelcome:Record<string,string>={总览:`欢迎回来，${account.name}`,提交建议:'欢迎提交建议',我的建议:'欢迎查看你的创新足迹',建议广场:'欢迎发现优秀创新建议',审核管理:'欢迎处理待审核建议',系统管理:'欢迎管理平台配置',超级维护:'欢迎进行平台维护'};
const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
const visible=nav.filter(([n])=>role==='灵感捕手'?!['审核管理','系统管理','超级维护'].includes(n):role==='建议初审'?!['系统管理','超级维护'].includes(n):true);
const action=(id:string,status:Status,msg:string)=>{setItems(v=>v.map(x=>x.id===id?{...x,status,...(status==='已采纳'?{adoptedAt:new Date().toISOString()}:{} )}:x));setSelected(null);flash(msg)};
const toggle=(id:string,key:'liked'|'collected')=>setItems(v=>v.map(x=>x.id===id?{...x,[key]:!x[key],likes:key==='liked'?x.likes+(x[key]?-1:1):x.likes,saved:key==='collected'?x.saved+(x[key]?-1:1):x.saved}:x));
return <main className="shell"><aside className="side"><div className="brand"><b>微</b><div><strong>微创新</strong><small>INNOVATION HUB</small></div></div><nav>{visible.map(([n,i])=><button key={n} onClick={()=>setPage(n)} className={page===n?'active':''}><span>{i}</span>{n}{n==='审核管理'&&<em>5</em>}</button>)}</nav><div className="power"><span>本月创新力</span><strong>86</strong><i><b/></i><small>超过 78% 的同事</small></div><div className="user-wrap">{userMenu&&<div className="user-pop"><button onClick={()=>{setAccount(null);setUserMenu(false);setPage('总览')}}>↪ 退出登录</button></div>}<button className="user" onClick={()=>setUserMenu(!userMenu)}><i>{account.name[0]}</i><div><b>{account.name}</b><small>{role} · {account.points}积分</small></div><span>⌃</span></button></div></aside>
<section className="content"><header><div className="header-left"><div className="top-context"><small>MICRO INNOVATION PLATFORM</small><b>{page}</b><span>{pageWelcome[page]||`欢迎使用${page}`}</span></div>{!['总览','提交建议'].includes(page)&&<div className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder={page==='我的建议'?'搜索建议标题或问题描述':'搜索建议、提交人或部门'}/><kbd>⌘ K</kbd></div>}</div><div className="actions"><button className="bell message-button" onClick={()=>setNotice(!notice)}>♢ <span>消息提示</span><i>3</i></button><span className="role-badge">{role}</span></div>{notice&&<div className="notices"><b>消息通知</b><p>● 你的建议已通过终审</p><p>● 有 2 位同事评论了你的建议</p><p>● 设备借用流程等待你审核</p><button onClick={()=>{setNotice(false);flash('已全部标记为已读')}}>全部已读</button></div>}</header>
{page==='总览'&&<Dashboard items={items} go={setPage} open={setSelected} account={account}/>} {page==='提交建议'&&<Submit dept={account.dept} onSubmit={s=>{setItems([{...s,id:`MI-2026-0${items.length+43}`,author:account.name,date:'刚刚',status:'待审核',likes:0,comments:0,saved:0},...items]);setPage('我的建议');flash('建议提交成功，已进入待审核')}}/>}{['我的建议','建议广场','审核管理','超级维护'].includes(page)&&<List page={page} items={filtered} filter={filter} setFilter={setFilter} open={setSelected} toggle={toggle}/>} {page==='系统管理'&&<Admin flash={flash}/>}</section>
{selected&&<Drawer item={items.find(x=>x.id===selected.id)||selected} page={page} close={()=>setSelected(null)} action={action} toggle={toggle}/>} {toast&&<div className="toast">✓ {toast}</div>}</main>}
function Login({onLogin}:{onLogin:(a:Account)=>void}){const[name,setName]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();const found=accounts.find(a=>a.name===name.trim());if(!found||password!=='123456'){setError('姓名或密码错误，请使用下方测试账号');return}onLogin(found)};return <main className="login-page"><section className="login-intro"><div className="login-brand"><b>微</b><span>微创新<small>INNOVATION HUB</small></span></div><div><small>MAKE SMALL IDEAS MATTER</small><h1>让每一个微小改进<br/>都被看见。</h1><p>汇聚一线灵感，推动持续改善，让好想法真正落地。</p></div><footer>微创新建议平台 · 企业内部测试环境</footer></section><section className="login-panel"><form onSubmit={submit}><span className="login-kicker">WELCOME BACK</span><h2>登录微创新平台</h2><p>请输入测试账号进入对应角色工作台</p><label>姓名<input value={name} onChange={e=>{setName(e.target.value);setError('')}} placeholder="请输入姓名" autoFocus/></label><label>密码<input type="password" value={password} onChange={e=>{setPassword(e.target.value);setError('')}} placeholder="请输入密码"/></label>{error&&<div className="login-error">! {error}</div>}<button className="primary">登录平台 →</button><div className="test-accounts"><b>测试账号</b>{accounts.map(a=><button type="button" key={a.name} onClick={()=>{setName(a.name);setPassword('123456');setError('')}}><span>{a.name}</span><small>{a.role}</small></button>)}<p>所有账号统一密码：<strong>123456</strong></p></div></form></section></main>}
function Dashboard({items,go,open,account}:{items:Idea[];go:(s:string)=>void;open:(x:Idea)=>void;account:Account}){const[now,setNow]=useState(()=>new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer)},[]);const hour=now.getHours();
const greeting=hour<5?'凌晨好':hour<11?'早上好':hour<14?'中午好':hour<18?'下午好':'晚上好';
const currentDate=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(now);
const mine=items.filter(x=>x.author===account.name);
const mineAdopted=mine.filter(x=>x.status==='已采纳');
const pendingMine=mine.filter(x=>x.status==='待审核'||x.status==='待终审').slice(0,3);
const reviewCount=account.role==='灵感捕手'?0:account.role==='建议初审'?items.filter(x=>x.status==='待审核').length:items.filter(x=>x.status==='待终审').length;const latestAdopted=[...items].filter(x=>x.status==='已采纳').sort((a,b)=>(b.adoptedAt||'').localeCompare(a.adoptedAt||'')).slice(0,2);const leaders=[['1','周文清','智能制造部','240'],['2','陈嘉言','数字化中心','190'],['3','顾宁','综合管理部','165'],['4','许知远','研发中心','158'],['5','沈悦','安全环保部','146'],['6','赵一帆','质量管理部','138'],['7','苏宁川','市场运营部','129'],['8','林澄','生产运营部','120'],['9','唐若溪','供应链部','112'],['10','陆明','财务管理部','105']];return <div className="page"><div className="welcome"><div><span>{currentDate}</span><h1>{greeting}，{account.name} <i>✦</i></h1><p>每一个小想法，都可能成为改变的起点。</p></div><button onClick={()=>go('提交建议')}>说说你的新想法　→</button></div><div className="stats"><Stat n={String(mine.length)} l="我的建议" d="当前账号提交总数" c="mint"/><Stat n={String(mineAdopted.length)} l="已采纳" d={`累计获得 ${mineAdopted.length*10} 积分`} c="peach"/><Stat n={String(reviewCount)} l="待我审核" d={account.role==='灵感捕手'?'当前角色无需审核':'等待当前角色处理'} c="lilac"/><Stat n={String(account.points)} l="创新积分" d="创新贡献持续积累" c="blue"/></div><div className="grid"><section className="panel queue"><Head e="MY PENDING IDEAS" t="待处理建议" on={()=>go('我的建议')}/>{pendingMine.length?pendingMine.map(x=><IdeaRow key={x.id} x={x} open={open}/>):<p className="empty-state">当前没有待处理的个人建议</p>}</section><section className="panel rank"><Head e="INSPIRATION · TOP 10" t="创新先锋"/><div className="rank-list">{leaders.map(r=><article className={r[1]===account.name?'me':''} key={r[0]}><strong>{r[0]}</strong><i>{r[1][0]}</i><p><b>{r[1]}</b><small>{r[2]}</small></p><span>{r[3]}<small> 积分</small></span></article>)}</div></section></div><section className="panel adopted"><Head e="LATEST ADOPTED" t="最新采纳" on={()=>go('建议广场')}/><div>{latestAdopted.map(x=><article onClick={()=>open(x)} key={x.id}><span>{x.dept}</span><time>{x.adoptedAt?new Date(x.adoptedAt).toLocaleDateString('zh-CN'):'-'}</time><h3>{x.title}</h3><p>{x.desc}</p><footer>{x.author}<b>♡ {x.likes}　◌ {x.comments}</b></footer></article>)}</div></section></div>}
function Head({e,t,on}:{e:string;t:string;on?:()=>void}){return <div className="head"><div><small>{e}</small><h2>{t}</h2></div>{on&&<button onClick={on}>查看全部 →</button>}</div>}
function Stat({n,l,d,c}:{n:string;l:string;d:string;c:string}){return <div className={'stat '+c}><i>✦</i><div><strong>{n}</strong><b>{l}</b><small>{d}</small></div></div>}
function IdeaRow({x,open}:{x:Idea;open:(x:Idea)=>void}){return <article className="idea" onClick={()=>open(x)}><i>{x.dept[0]}</i><div><span className={'status '+x.status}>{x.status}</span><small>{x.id} · {x.date}</small><h3>{x.title}</h3><p>{x.desc}</p><footer>{x.author} · {x.dept}<b>查看详情 →</b></footer></div></article>}
function Submit({onSubmit,dept}:{onSubmit:(x:any)=>void;dept:string}){const[f,setF]=useState({title:'',desc:'',plan:'',dept}),[polishing,setPolishing]=useState(false),[suggestion,setSuggestion]=useState(''),[aiError,setAiError]=useState('');
const runPolish=async()=>{if(!f.title.trim()||polishing)return;setPolishing(true);setSuggestion('');setAiError('');try{const response=await fetch('/api/polish-title',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:f.title})});const data=await response.json() as {title?:string;error?:string};if(!response.ok||!data.title)throw new Error(data.error||'AI 润色失败');setSuggestion(data.title)}catch(error){setAiError(error instanceof Error?error.message:'AI 润色暂时不可用')}finally{setPolishing(false)}};
return <div className="page narrow"><Title e="NEW IDEA" h="提交一条微创新" p="清楚描述问题和改进思路，让好想法更快落地。"/>
<form className="panel form" onSubmit={e=>{e.preventDefault();onSubmit(f)}}>
<Field t="建议标题 *" count={`${f.title.length}/50`}><div className="title-input"><input required maxLength={50} value={f.title} onChange={e=>{setF({...f,title:e.target.value});setSuggestion('');setAiError('')}} placeholder="例如：优化会议室预约流程"/><button type="button" className="ai-polish" disabled={!f.title.trim()||polishing} onClick={runPolish}><i>✦</i>{polishing?'润色中…':'AI 润色'}</button></div>
{aiError&&<p className="ai-error">! {aiError}</p>}
{suggestion&&<div className="ai-suggestion"><div><span><i>✦</i> AI 润色建议</span><small>表达更清晰、行动导向更明确</small></div><p>{suggestion}</p><footer><button type="button" onClick={()=>setSuggestion('')}>取消</button><button type="button" onClick={runPolish}>换一个</button><button type="button" className="use-suggestion" onClick={()=>{setF({...f,title:suggestion});setSuggestion('')}}>采用此标题</button></footer></div>}
</Field><Field t="问题描述 *" count={`${f.desc.length}/500`}><textarea required maxLength={500} value={f.desc} onChange={e=>setF({...f,desc:e.target.value})} placeholder="请描述当前问题、发生场景及影响…"/></Field><Field t="改进方案" count={`${f.plan.length}/500`}><textarea maxLength={500} value={f.plan} onChange={e=>setF({...f,plan:e.target.value})} placeholder="你的具体方案和预期效果…"/></Field>
<Field t="所属部门 *"><input value={dept} readOnly aria-readonly="true" title="所属部门与当前账号绑定，不可修改"/><small className="field-hint">部门由当前账号自动带入，不可修改</small></Field>
<div className="upload">＋<b>点击或拖拽上传附件</b><small>图片、PDF、Office 文件，单个不超过 10MB</small></div>
<div className="form-buttons"><button type="button">保存草稿</button>
<button className="primary">提交建议 →</button></div></form></div>}
function Field({t,count,children}:{t:string;count?:string;children:React.ReactNode}){return <label>{t}<small>{count}</small>{children}</label>}
function Title({e,h,p}:{e:string;h:string;p:string}){return <div className="title"><small>{e}</small><h1>{h}</h1><p>{p}</p></div>}
function List({page,items,filter,setFilter,open,toggle}:{page:string;items:Idea[];filter:string;setFilter:(s:string)=>void;open:(x:Idea)=>void;toggle:(id:string,k:'liked'|'collected')=>void}){const list=page==='建议广场'?items.filter(x=>x.status==='已采纳'):page==='审核管理'?items.filter(x=>['待审核','待终审'].includes(x.status)):items;return <div className="page"><Title e="IDEAS & IMPROVEMENTS" h={page} p={page==='建议广场'?'发现值得被看见的好想法，与同事一起参与改进。':page==='审核管理'?'请及时查看建议内容并完成流程处理。':'管理建议全生命周期与可见状态。'}/>{page!=='建议广场'&&<div className="tabs">{['全部','待审核','待终审','已采纳','已退回'].map(t=><button className={filter===t?'active':''} onClick={()=>setFilter(t)} key={t}>{t}</button>)}</div>}<div className="cards">{list.map(x=><article className="card" key={x.id} onClick={()=>open(x)}><div><span className={'status '+x.status}>{x.status}</span><small>{x.id}</small></div><h3>{x.title}</h3><p>{x.desc}</p><aside><i>{x.author[0]}</i>{x.author} · {x.dept}<time>{x.date}</time></aside><footer><button onClick={e=>{e.stopPropagation();toggle(x.id,'liked')}}>♡ {x.likes}</button><button>◌ {x.comments}</button><button onClick={e=>{e.stopPropagation();toggle(x.id,'collected')}}>☆ {x.saved}</button><b>查看详情 →</b></footer></article>)}</div></div>}
function Drawer({item,page,close,action,toggle}:{item:Idea;page:string;close:()=>void;action:(id:string,s:Status,m:string)=>void;toggle:(id:string,k:'liked'|'collected')=>void}){return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className={'status '+item.status}>{item.status}</span><small>{item.id} · {item.date}</small><h2>{item.title}</h2><div className="author"><i>{item.author[0]}</i><b>{item.author}<small>{item.dept}</small></b></div><hr/><h4>问题描述</h4><p>{item.desc}</p><h4>改进方案</h4><p>{item.plan}</p><div className="social"><button onClick={()=>toggle(item.id,'liked')}>♡ {item.likes} 点赞</button><button onClick={()=>toggle(item.id,'collected')}>☆ {item.saved} 收藏</button><button>◌ {item.comments} 评论</button></div>{page==='审核管理'&&<div className="review"><label>审核意见<textarea placeholder="请填写审核意见（最多200字）"/></label><div><button onClick={()=>action(item.id,'已退回','已退回给提交人调整')}>退回调整</button>{item.status==='待审核'&&<button onClick={()=>action(item.id,'待终审','已提交终审')}>提交终审</button>}<button className="primary" onClick={()=>action(item.id,'已采纳','建议已采纳并公示')}>采纳并公示</button></div></div>}</aside></div>}
function Admin({flash}:{flash:(s:string)=>void}){return <div className="page"><Title e="SYSTEM SETTINGS" h="系统管理" p="配置角色菜单权限与企业部门结构。"/><div className="admin">{['灵感捕手','审核员','建议终审'].map((r,i)=><section className="panel" key={r}><i>{['灵','审','终'][i]}</i><h3>{r}</h3><p>{['普通员工，提交与参与建议互动','负责建议初审及直接采纳','负责终审和平台管理'][i]}</p>{nav.slice(1).map(([n])=><label key={n}><input type="checkbox" defaultChecked={i===2||i===1&&!['系统管理','超级维护'].includes(n)||i===0&&!['审核管理','系统管理','超级维护'].includes(n)}/>{n}</label>)}<button onClick={()=>flash(`${r}权限配置已保存`)}>保存配置</button></section>)}</div></div>}
